project_id = "rehcfgqvigfcekiipqkc"

[functions.webhook-a010-sales]
verify_jwt = false

[functions.hubla-webhook-handler]
verify_jwt = false

[functions.import-weekly-metrics]
verify_jwt = false

[functions.clint-api]
verify_jwt = false

[functions.import-contacts-csv]
verify_jwt = false

[functions.import-deals-csv]
verify_jwt = false

[functions.process-csv-imports]
verify_jwt = false

[functions.sync-clint-data]
verify_jwt = false

[functions.sync-origins-stages]
verify_jwt = false

[functions.sync-contacts]
verify_jwt = false

[functions.sync-deals]
verify_jwt = false

[functions.sync-link-contacts]
verify_jwt = false

[functions.sync-by-origin]
verify_jwt = false

[functions.clint-webhook-handler]
verify_jwt = false

[functions.webhook-metrics-receiver]
verify_jwt = false

[functions.recalculate-metrics]
verify_jwt = false

[functions.import-spreadsheet-data]
verify_jwt = false

[functions.webhook-funnel-targets]
verify_jwt = false

[functions.import-bubble-history]
verify_jwt = false